apiVersion: v1
kind: Secret

metadata:
  name: fastapi-secret

type: Opaque

stringData:
  DB_HOST: {{ .Values.secret.DB_HOST | quote }}
  DB_PORT: {{ .Values.secret.DB_PORT | quote }}
  DB_NAME: {{ .Values.secret.DB_NAME | quote }}
  DB_USER: {{ .Values.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}